FROM node:alpine

WORKDIR /app

COPY package.json /app

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp

COPY . /app

EXPOSE 3000
CMD ["npm", "run", "start"]